### ISSUE TITLE
consider including a SPARQL UI

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/k-gap#18]

**Comment by marc-portier** [comment]
popular candidate for this is https://yasgui.triply.cc/

it actually works in the browser and can connect to any endpoint, but there might be an easy way to stuff it into a docker-container of some sorts and then include it in our docker-compose stack?

and *lo and behold* --> that happens to exist: https://github.com/redpencilio/docker-yasgui
and is coming from known peeps (@erikap from @redpencilio fame)
