### ISSUE TITLE
Increase the max allowed httpHeaderSize

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/k-gap#3]
According to https://stackoverflow.com/questions/64112724/how-to-increase-max-header-size-for-graphdb-standalone-server we could be modifying the default 4096 limit on HHTP-POST for triples to ingest via sparql through setting
```
graphdb.connector.maxHttpHeaderSize = 65536
```

This should be doable through inserting something like `-Dgraphdb.connector.maxHttpHeaderSize=${GDB_MAX_HEADER:-65536}` into the statement at the end of `graphdb/kgap/entrypoint-wrap.sh` (at https://github.com/vliz-be-opsci/k-gap/blob/main/graphdb/kgap/entrypoint-wrap.sh#L31)

this in combination with 
- introducing this env variable in dotenv-example and/or README
- introducing setting it in the sample docker-compose.yml

Hopefully that covers the issue mentioned in https://github.com/vliz-be-opsci/py-RDF-store/issues/12

**Comment by laurianvm** [comment]
was solved through PR #20
